// legacy_react/components/StatCard.tsx
import React from 'react';

interface StatCardProps {
  title: string;
  value: string | number;
  trend?: string;
  icon: string;
  color: string;
}

const StatCard: React.FC<StatCardProps> = ({ title, value, trend, icon, color }) => {
  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 flex items-start justify-between">
      <div>
        <p className="text-sm font-medium text-slate-500 mb-1">{title}</p>
        <h3 className="text-2xl font-bold text-slate-800">{value}</h3>
        {trend && (
          <p className="text-xs font-medium text-emerald-600 mt-2 flex items-center">
            <span>↑</span>
            <span className="ml-1">{trend} this week</span>
          </p>
        )}
      </div>
      <div className={`p-3 rounded-lg ${color} bg-opacity-10`}>
        <span className="text-2xl">{icon}</span>
      </div>
    </div>
  );
};

export default StatCard;

// src/components/StatCard.vue
<script setup lang="js">
defineProps({
  title: String,
  value: [String, Number],
  icon: String,
  color: String,
  trend: String,
});
</script>

<template>
  <div class="bg-white p-4 md:p-5 rounded-2xl shadow-sm border border-slate-100 flex items-center justify-between">
    <div>
      <p class="text-[11px] md:text-xs font-semibold text-slate-500">{{ title }}</p>
      <p class="text-xl md:text-2xl font-bold text-slate-900 mt-1">{{ value }}</p>
      <p v-if="trend" class="text-[11px] text-emerald-600 font-semibold mt-1">↑ {{ trend }} this week</p>
    </div>
    <div class="w-11 h-11 md:w-12 md:h-12 rounded-2xl flex items-center justify-center text-lg md:text-xl shadow-inner"
      :class="[color, 'bg-opacity-10 text-slate-700 border border-slate-100']">
      {{ icon }}
    </div>
  </div>
</template>
